name = "ImageProcessing"
uuid = "45b7010d-6bd2-4dbe-aaef-5f0c144f0fe8"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]
version = "0.1.0"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
TypeUtils = "c3b1956e-8857-4d84-9b79-890df85b1e67"

[compat]
OffsetArrays = "1.14.1"
TypeUtils = "1.4.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
